# Site settings
title: Rob Hinds
twitter_username: rob_hinds
name: Rob Hinds

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/robhinds
 - title: StackOverflow
   url: https://stackoverflow.com/users/258813/rhinds
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1
 - title: Food
   url: https://www.robbishfood.com/

#Any buzzword skills you want to include
skills:
 - Scala
 - Akka-http
 - Microservices
 - Slick
 - Product management
 - API design
 - Groovy
 - Spring MVC/Boot/Social
 - Gradle
 - Java
 - JPA
 - SQL
 - REST
 - Technical Architecture
 - Machine learning

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: CTO
   start: 2017
   end: Ongoing
   employer: Basement Crowd
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Engineer
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/genotype
 - robhinds/footweets
 - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/258813/rhinds
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  Para disponibilizar nossos serviços, precisamos coletar alguns dados de nossos usuários. Nós não coletamos dados que não serão necessários para o funcionamento de nossos serviços. Precisamos deixar claro que, este documento pode ser alteado a qualquer momento, por isso, auxiliamos que sempre que for utilizar de nossos serviços, cheque este documento para entender como nós tratamos o que usamos.<br/><br/>
  <strong>Dados que Coletamos</strong>: Nós armazenamos somente seu ID/Nick do Discord, que é uma informação pública que todos possuem acesso. Este é o único dado dos usuários que nós coletamos e armazenamos para conseguir identificar e ordenar informações do banco de dados referentes a cada perfil. <br/><br/>
  <strong>Proteção de Dados</strong>: Todos os dados são acessíveis por e somente Um indivíduo (Para o dono Do Cj Rebaixado). Ele garante que nenhum dado será distribuído, vendido ou doado para terceiros. Ele também demonstra que os dados estão salvos de forma segura em um Banco de Dados robusto em questões de segurança. <br/><br/>
  <strong>Serviços de Terceiros</strong>: Cj Rebaixado é um aplicativo que roda dentro do Discord, por isso, segue as regras e normas de lá, assim como seus usuários o devem fazer. <br/><br/>
  <strong>Exclusão de Dados</strong>: O usuário pode ter seus dados apagados Da Aplicação a qualquer momento enviando Uma solicitação Direta via DM com o desenvolvedor ou via support server no menu de ajuda. 
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  Ao utilizar qualquer serviço do Cj Rebaixado, você deve ter a conciência de tudo que você pode e não pode fazer. Ao utilizá-la, levamos em conta que você LEU e CONCORDA com todos estes termos.<br/><br/>
  <strong>Abuso de Bugs</strong>: Ao encontrar um bug, e ao invés de reportá-lo, você abusa dele e/ou, até compartilha ele, você está sujeito a perder o acesso à todos serviços do Cj Rebaixado. Além disso, ao presenciar um bug e não reportá-lo, você está sujeito a perder o acesso à todas funcionalidades do Bot.<br/><br/>
  <strong>Idade</strong>: Para utilizar o Cj Rebaixado, você deve ter no mínimo 13 anos de idade. Pessoas menores da idade legal devem ter o consentimento do Responsável legal sobre estes termos antes de utilizá-lo.<br/><br/>
  <strong>Diretrizes da Comunidade</strong>: Como O Cj Rebaixado é uma aplicação dependente de uma aplicação principal (Discord), o usuário deve, além de seguir as seguintes regras, seguir também as diretrizes desta. Veja as diretrizes do Discord.<br/><br/>
  Não utilize conteúdos NSFW (conteúdos adultos ou sensíveis) em comandos do Cj Rebaixado. Nós não queremos nenhum tipo de vínculo com este tipo de conteúdo.Não toleramos qualquer tipo de atitude racista, homofóbica, xenofóbica, preconceituosa, entre outros com qualquer pessoa. Nossa missão com o Cj Rebaixado é divertir os servidores, caso seu servidor promove ou possui vínculo com atitudes que denigrem a imagem de alguém, então nós não queremos vínculos com você.<br/><br/> 
  Tentar burlar restições impostas pela aplicação, como algo que desvia de um tempo de recarga, ou utilizar outras contas para melhorar uma conta principal é proibído.<br/><br/>
  <strong>Apelo de Banimento</strong>: Caso queira rever o seu banimento, você pode entrar em contato com o suporte Na aba de suporte menu de ajuda do Cj Rebaixado.
